#!/bin/sh

set -e

cd "$(dirname $0)"
if [ -f .build_number ]; then
    BUILD_NUMBER=$(expr $(cat .build_number) + 1)
else
    BUILD_NUMBER=1
fi
echo $BUILD_NUMBER > .build_number
export BUILD_NUMBER

gradle clean build

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

ln -sfn $PWD/build/libs/stuff-0.0.$BUILD_NUMBER.jar $tmpdir/stuff-0.0.$BUILD_NUMBER.jar
mkdir $tmpdir/stuff_service
ln -sfn $PWD/run_service $tmpdir/stuff_service/run

tar --dereference -C $tmpdir -c -f - . | ssh harvestman "tar -x -v -f - && ln -sfvn stuff-0.0.$BUILD_NUMBER.jar stuff-latest.jar && svc -t stuff_service"
