#!/bin/sh

set -e

cd "$(dirname $0)"
if [ -f .build_number ]; then
    BUILD_NUMBER=$(expr $(cat .build_number) + 1)
else
    BUILD_NUMBER=1
fi
echo $BUILD_NUMBER > .build_number
export BUILD_NUMBER

gradle clean build

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

artifact=stuff

mkdir $tmpdir/packages $tmpdir/service
ln -sfn $PWD/build/libs/$artifact-0.0.$BUILD_NUMBER.jar $tmpdir/packages/$artifact-0.0.$BUILD_NUMBER.jar
ln -sfn $PWD/run_service $tmpdir/service/run

tar --dereference -C $tmpdir -c -f - packages service | ssh harvestman "sudo -u $artifact-jadm sh -c 'cd /srv/$artifact-japp && tar -x -v -f - && ln -sfvn $artifact-0.0.$BUILD_NUMBER.jar packages/$artifact-latest.jar && if [ -p service/supervise/control ]; then svstat service && svc -t service; else echo no supervise; fi'"
