#!/bin/sh

set -e

cd "$(dirname $0)"
if [ -f .build_number ]; then
    BUILD_NUMBER=$(expr $(cat .build_number) + 1)
else
    BUILD_NUMBER=1
fi
echo $BUILD_NUMBER > .build_number
export BUILD_NUMBER

gradle clean build

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

artifact=stuff

ln -sfn $PWD/build/libs/$artifact-0.0.$BUILD_NUMBER.jar $tmpdir/$artifact-0.0.$BUILD_NUMBER.jar
mkdir $tmpdir/${artifact}_service
ln -sfn $PWD/run_service $tmpdir/${artifact}_service/run

tar --dereference -C $tmpdir -c -f - . | ssh harvestman "tar -x -v -f - && ln -sfvn $artifact-0.0.$BUILD_NUMBER.jar $artifact-latest.jar && svc -t ${artifact}_service"
