#!/bin/sh

set -e

runtime_deps() {
    gradle_artifact_cache=$(ls -d $HOME/.gradle/caches/artifacts-*/filestore | head -n 1)
    cat build/resources/main/META-INF/stuff.deps.txt | while read id type; do
	set -- $(echo $id | tr ':' ' ')
	group="$1"
	name="$2"
	version="$3"
	file="$name-$version.jar"
	resolved=$(find $gradle_artifact_cache -name "$file")
	if [ -z "$resolved" ]; then
	    echo "Unable to resolve $group:$name:$version in Gradle cache" >&2
	    exit 1
	fi
	echo $resolved
    done
}

classpath=$( runtime_deps | while read jar; do echo -n "$jar:"; done )

if [ -z "$JAVA" ]; then
    if [ -n "$JAVA_HOME" ]; then
	JAVA=$JAVA_HOME/bin/java
    fi
fi

exec ${JAVA-java} ${JAVA_OPTS} -classpath "$classpath:build/classes/main:build/resources/main" org.araqnid.stuff.Main
