#!/bin/sh

set -e

die() {
    echo "$0: $@" >&2
    exit 1
}

artifact="stuff"
apprepo="$HOME/packages"
latestlink="$apprepo/$artifact-latest.jar"
[ -L "$latestlink" ] || die "Not a symlink: $latestlink"
latestjar=$(readlink -f "$latestlink")
[ -f "$latestjar" ] || die "Failed to resolve $latestlink to a usable filename (got $latestjar)"
depsfile=$(dirname $latestjar)/$(basename $latestjar .jar).deps
[ -f "$depsfile" ] || die "No dependencies file for $latestjar"

if [ -z "$JAVA" ]; then
    if [ -z "$JAVA_HOME" -a -f "java_home" ]; then
	JAVA_HOME=$(cat java_home)
    fi
    if [ -n "$JAVA_HOME" ]; then
	JAVA=$JAVA_HOME/bin/java
    fi
fi

if [ -z "$JAVA_OPTS" -a -f "java_options" ]; then
    JAVA_OPTS=$(cat java_options)
fi

mainclass=$( unzip -qc $latestjar META-INF/MANIFEST.MF | awk '$1 == "X-Service-Class:" { print $2 }' | sed -e 's/\r//' )

if [ -z "$PORT" -a -f "port" ]; then
    PORT=$(cat port)
    export PORT
fi

if [ -f "appuser" ]; then
    appuser=$(cat appuser)
else
    appuser=$(id -un)
fi

classpath="$latestjar$(while read file; do echo -n ":$file"; done < $depsfile)"

if [ -f "environment" ]; then
    . ./environment
fi

exec ${JAVA-java} ${JAVA_OPTS} -classpath "$classpath" "$mainclass"
